/** @type {import('tailwindcss').Config} */
const plugin = require("tailwindcss/plugin");
const { createThemes } = require('tw-colors');
import { createThemeFonts } from './src/utils/index';

module.exports = {
  content: ["./src/**/*.{html,js}"],

  plugins: [
    // require('@tailwindcss/forms'),
    require("@tailwindcss/typography"),
    // require('tailwindcss/aspect-ratio'),
    // require('@tailwindcss/container-queries'),
    createThemes(
      {
        patchWRK: {
          main: "white",
          tertiary: "#f9fafb",
          inactive: "#bfdbfe",
          secondary: "#94a3b8",
          "accent-light": "#64748b",
          "trim-light": "#64748b",
          "accent-dark": "#1d4ed8",
          primary: "#1e3a8a",
          "trim-dark": "#1e3a8a",
          info: "#0a0a0a",
          success: "#22C55E",
          error: "#F97316",
          warning: "#DC2626",
        },
        nyias: {
          main: "white",
          tertiary: "#f9fafb",
          inactive: "#e5e5e5",
          secondary: "#f87171",
          "accent-light": "#ef4444",
          "trim-light": "#ef4444",
          "accent-dark": "#404040",
          primary: "#171717",
          "trim-dark": "#171717",
          info: "#0a0a0a",
          success: "#22C55E",
          error: "#F97316",
          warning: "#DC2626",
        },
        dragons: {
          main: "white",
          tertiary: "#f9fafb",
          inactive: "#e9d5ff",
          secondary: "#facc15",
          "accent-light": "#eab308",
          "trim-light": "#eab308",
          "accent-dark": "#7e22ce",
          primary: "#581c87",
          "trim-dark": "#581c87",
          info: "#0a0a0a",
          success: "#22C55E",
          error: "#F97316",
          warning: "#DC2626",
        },
        grey: {
          main: "white",
          tertiary: "#FAFAFA",
          inactive: "#F5F5F5",
          secondary: "#737373",
          "accent-light": "#525252",
          "trim-light": "#525252",
          "accent-dark": "#262626",
          primary: "#171717",
          "trim-dark": "#171717",
          info: "#0a0a0a",
          success: "#22C55E",
          error: "#F97316",
          warning: "#DC2626",
        },
        forest: {
          main: "white",
          tertiary: "#FFFBEB",
          inactive: "#FEF3C7",
          secondary: "#B45309",
          "accent-light": "#92400E",
          "trim-light": "#92400E",
          "accent-dark": "#14532D",
          primary: "#052E16",
          "trim-dark": "#052E16",
          info: "#0A0A0A",
          success: "#22C55E",
          error: "#F97316",
          warning: "#DC2626",
        },
        racer: {
          main: "white",
          tertiary: "#FAFAFA",
          inactive: "#E0F2FE",
          secondary: "#FDE047",
          "accent-light": "#B91C1C",
          "trim-light": "#B91C1C",
          "accent-dark": "#0EA5E9",
          primary: "#0284C7",
          "trim-dark": "#0284C7",
          info: "#0A0A0A",
          success: "#22C55E",
          error: "#F97316",
          warning: "#DC2626",
        },
        "retro-diner": {
          main: "white",
          tertiary: "#FFFBEB",
          inactive: "#FECDD3",
          secondary: "#F43F5E",
          "accent-light": "#FB923C",
          "trim-light": "#FB923C",
          "accent-dark": "#0D9488",
          primary: "#451A03",
          "trim-dark": "#451A03",
          info: "#0A0A0A",
          success: "#22C55E",
          error: "#F97316",
          warning: "#DC2626",
        },
      },
      {
        defaultTheme: "grey",
        strict: true,
      }
    ),
    createThemeFonts({
      forest: {
        body: '"Tenor Sans", sans-serif',
        display: '"Merienda", cursive',
      },
      racer: {
        body: "Montserrat",
        display: "Anton",
      },
      "retro-diner": {
        body: "Montserrat",
        display: "Roboto Slab",
      },
    }),
  ],
  theme: {
    extend: {
      spacing: {
        "8xl": "96rem",
        "9xl": "128rem",
      },
      borderRadius: {
        "4xl": "2rem",
      },
      borderWidth: {
        1: "1px",
        3: "3px",
      },
    },
  },
};